server:
  servlet:
    context-path: /server
  port: 8080

spring:
  redis:
    host: cnzzi.cn
    port: 6379

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cnzzi.cn:3306/security?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 199608


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.starlz.server.entity


logging:
  level:
    root: debug
