server:
  port: 8082
  session:

  servlet:
    context-path: /client
    session:
      cookie:
        name: UISESSION
security:
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8080/server/oauth/token
      userAuthorizationUri: http://localhost:8080/server/oauth/authorize
      registered-redirect-uri: http://localhost:8082/client/login
    resource:
      userInfoUri: http://localhost:8080/server/user/me
spring:
  thymeleaf:
    cache: false
